### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#158]
# Problem

All of the Waku tests are currently related to a single node, especially those related to the various protocols such as `filter` and `store`. To really ensure assertion of these protocols in a network, this is not enough however. 

# Solution

We should create a multi node test that tests the various protocols. Eg, we relay a message from one node. Try to filter from another and call the `store` methods from yet another. This will indicate whether or not all these nodes work as planned in an almost production enviroment.

# Nice to haves
 - Ideally these tests would be packaged in such a way that providing IP addresses we could run the tests with x nodes automatically, meaning we could run them against our testnet.

**Comment by kdeme** [comment]
While I think it would be nice to have an (automated) local testnet / simulation set-up, especially if we can then also use it to set up a "remote" testnet for several to test against. It would help testing more situtations (due to more realistic message delays), but it is probably not the first step.

I think it is probably easier to first have some "in process" nodes communicating which each other.
Especially for the 3 protocol:
- WakuRelay (although this is kinda repeating GossipSub and FloodSub tests but with the selector)
- WakuFilter
- WakuStore

And probably also for the WakuNode protocol (first test exists there).
Personally, I think it is more fast to use the latter type of tests to develop against, and also useful as a first line of CI checks.

**Comment by oskarth** [comment]
Agree. The current issue is also too complex. I suggest creating an issue for the biggest pain point in something that can be solved in a few hours or a day of hacking.

**Comment by oskarth** [comment]
Creating a test issue to spin up three nodes that test this topology https://github.com/status-im/nim-waku/issues/221 seems useful as an initial step.

**Comment by jm-clius** [comment]
@oskarth, as far as I can tell this issue can be closed? Even while we still don't run tests against our testnet, we now have several CI tests that spins up multiple local nodes. Feel free to re-open if you think this still requires visibility.
