### ISSUE TITLE
RFC: Waku v2 JSON-RPC REST API design and direction

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#243]
## Problem

We need an API for non-Nim clients. This should be maximally accessible for various users, and where that isn't possible there should be a clear path towards it. It should minimize risks around integration as well as have minimal dependencies on as of yet developed infrastructure.

## Context

We need an API for clients that don't use Nim directly. This could either be applications like Status, or some new browser based application.

In Status with Waku v1 this is provided for Waku v1 and a JSON RPC API. This also takes care of encryption, etc. In Waku v2 this is optional and we want to keep it separate, at the same time enabling it for users who wish to have it. This reduces unknowns and makes apps like Status more likely to integrate it.

Additionally, we want to follow where Nimbus and Eth2 is going with exposing a REST-based HTTP API. Unfortunately, this isn't doable in Nim right now do the lack of a secure web server. The approach that Nimbus is taking is to expose a REST JSON RPC API and then making sure it can be mapped to a REST HTTP API.

In terms of technical risk and consistency, this seems like a sane approach to follow. Later on, this can be extended with more advanced models such as long polling, SSE, Websockets, etc.

Issues:
- Nimbus REST API: https://github.com/status-im/nimbus-eth2/issues/993
- Waku v2 JSON RPC: https://github.com/status-im/nim-waku/issues/203

APIs:
- Waku v1 JSON RPC API: https://specs.vac.dev/specs/waku/v1/waku-rpc-api.html
- Geth JSON RPC API
https://geth.ethereum.org/docs/rpc/ns-admin
- Whisper v6 API https://github.com/ethereum/go-ethereum/wiki/Whisper-v6-RPC-API
- status-react de facto ad hoc API https://github.com/status-im/status-react/blob/develop/src/status_im/ethereum/json_rpc.cljs (incl extensions made in status-go)
- Current hacky ad hoc Waku v2 JSON RPC API:
https://github.com/status-im/nim-waku/blob/master/waku/node/v2/rpc/wakucallsigs.nim
- Current Waku v2 Nim Node API: https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md
- Eth2 API: https://ethereum.github.io/eth2.0-APIs/
- Nimbus API: https://github.com/status-im/nimbus-eth2/blob/58dcca3364951892ddd5702afd66b203f7bb3d10/docs/the_nimbus_book/src/api.md

## Proposed solution

Specify a REST JSON RPC based API that can later be translated into a REST HTTP. Ensure this is stateless in terms of application state. Alternatively, design a REST HTTP API with e.g. Swagger and then map it to a JSON RPC implementation.

Use versioning and namespaced APIs to provide for common functionality, including what is provided for with Waku v1 JSON RPC w.r.t. encryption operations. Ensure there is no requirement on using this for normal routing of messages, etc.

Make a clear separation between which APIs are privileged vs not, i.e. can be used by an untrusted nodes vs something that is done locally.

## Details

This is a rough sketch and requires more thinking and a lot more details. It is written in HTTP style but translates naturally into JSON RPC, e.g. "GET /waku/v2/foobar" => "get_waku_v2_foobar".

Implicitly, and perhaps explicitly later, Waku v1 JSON RPC corresponds to: `POST/GET /waku/v1/foobar`.

```
## Private API
##
## These are API calls that require trusting the node. It should only be done on
## a local node, not remote. It is largely done for backwards compatibility with Waku v1.
##
## Usage is optional, and it may be done locally.
##
## Similar to https://specs.vac.dev/specs/waku/v1/waku-rpc-api.html

POST /waku/v2/private/symkey # store new symkey and return KeyID
GET /waku/v2/private/symkey/:id # return symkey based on KeyID

...and similar for public key crypto.

# TODO: POST/GET message filter here? How interact with "subscribe" and relay API?

## Admin API
##
## Operations that require the node to trust the client for changing its core operations.

/waku/v2/admin/

...start, init, stop?
...set protocol usage support, etc

## Debug API
##
## Operations used for debugging a node, read-only stuff.

/waku/v2/debug/

...node info, number of peers etc
...make separation between debug and admin clear w.r.t. privilege and usage
...look at how eth2 is doing it

## Relay API
##
## Calls for relay of messages.

POST /waku/v2/relay/publish message => status

# TODO Proper subscribe with handler here requires blocking, defer this until basics are in place. # Then we can use long polling/SSE/WS for events style API. Alternatively make this
# /head or /current? Look at eth2 API here.

# Mirrors existing API, though it is different from existing interface.
# Resource state vs application state. Think harder about this, as well as interaction with private API above.
# Calling it Foo as placeholder to make this different from future proper subscribe,
# Needs better name.
#
# Also, does it belong in the relay API?
POST /waku/v2/relay/subscribeFoo => Identifier

## Store API
##
## Calls for interacting with a store node.

GET /waku/v2/store/<HistoryQuery> => <HistoryResponse>

## Filter API
##
## Calls for filter API.

POST /waku/v2/filter/<filter-request> => status/ACK

# TODO Probably defer until basics are in place. MessagePush can be push-based, or long polling etc. See above.

```

## Suggested initial steps

1. Agreement on general direction
2. Cut up and do a minimal slice for 1 or 2 things end to end
   - e.g. store API
   - basic end to end with private API
3. Cut up further issues and triage
   - Make sure biggest unknowns addressed design-wise, but that that we do low hanging fruit stuff first

**Comment by oskarth** [comment]
cc @kdeme @decanus @jm-clius @staheri14

**Comment by oskarth** [comment]
Discussed during call, people agree with general direction. Some people might want more time to look over specifics.

**Comment by jm-clius** [comment]
Similar to @oskarth suggestion above I propose that we cut up the API work into the following three smaller issues:
### 1. Store protocol POC API
The aim of this would be to create the simplest possible POC that allows for historical queries via the API. A pagination option may be simple to add, but could even be excluded at this stage (i.e. only create endpoint to return _all_ history for a list of topics)
### 2. Spec: JSON-RPC REST API specification for Waku V2 (potentially already covered by [vacp2p/specs/#233](https://github.com/vacp2p/specs/issues/233))
Reach consensus on defined methods and specified behaviour for the v2 API. Publish **raw** version.
### 3. Implement: JSON-RPC REST API.
Extend POC API with the following functionality, roughly corresponding to @oskarth details above (likely in this order):

- Complete Store API (including pagination, if excluded from POC scope)
- Private API, Relay API and "Foo Subscribe" API (at this point basic end-to-end functionality could be shown)
- Filter API
- Basic Admin API, Debug API

After this point spec status could be changed to **draft**

## Notes:
* I've (sort of) started with a focus on (1) and propose we do it before spec write-up. This is because the query method should be fairly straightforward: something like `get_waku_v2_store_history` taking a list of topics and optional paging info as parameters, returning a HistoryResponse similar to described in [vacp2p/specs/#218](https://github.com/vacp2p/specs/issues/218). Leaving the paging info open should return all history for the selected topics. Quick glance at WakuStore with pagination changes shows that this can only be done in a stateless manner if interpreted server-side as a history query with pageSize set to max available messages (@staheri14 - is this correct?). Any lessons learned during the POC can then be addressed in the spec write-up.
* (3) could be further cut up as needed i.t.o. scheduling and triaging.
* For triaging I expect we can cut some Debug and Admin functionality from both **Spec** and **Implement** scopes, unless there are any reasons to swop priorities in the list?

**Comment by oskarth** [comment]
Sounds like a plan @jm-clius!

**Comment by staheri14** [comment]
>Quick glance at WakuStore with pagination changes shows that this can only be done in a stateless manner if interpreted server-side as a history query with pageSize set to max available messages (@staheri14 - is this correct?).

Sorry for my delayed reply.  My answer to your question: your interpretation is correct :)
