### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#275]
# Problem

Windows CI often fails for unclear reasons.

# Acceptance criteria

It works!

**Comment by oskarth** [comment]
cc @kdeme who looked into it before and @jm-clius FYI since you have a Windows machine. Not prio right now I believe.

**Comment by kdeme** [comment]
It would be good to post here the actual failures that sometimes occur in the CI.
Waku v1 has some occasional failures still, most likely because of usage of `await sleepAsync(...)`. those tests should be refactored as mentioned here already as the second bullet: https://github.com/status-im/nim-waku/issues/5

If there are specific tests that fail for waku v2, please add them here.
Typically, failures that occur sporadic on Windows but not on Linux or vice versa have to do with timings and races. Like a certain await that is being done but not actually guaranteed to have some action completed.

**Comment by oskarth** [comment]
Yeah, next time I see it I'll post here. Thanks for the context!

**Comment by jm-clius** [comment]
Unsure if this is related to these sporadic failures, but the Windows CI has been (consistently) failing since https://github.com/status-im/nim-waku/pull/310 was merged. Might be related to target/binary names changing. I'll take a look if I have a minute or on Monday morning.
```
build\wakunode.exe:` D:\a\_temp\735c93fb-d4d6-4ea1-989b-a2ade8dd352c.ps1:3
Line |
   3 |  build\wakunode.exe --help
     |  ~~~~~~~~~~~~~~~~~~
     | The module 'build' could not be loaded. For more information, run 'Import-Module build'.

Error: Process completed with exit code 1.
```

**Comment by jm-clius** [comment]
Moving to icebox for visibility. I've not seen this happen for a while now. Will keep monitoring.

**Comment by oskarth** [comment]
Possibly related? https://github.com/status-im/nimbus-eth1/pull/583
