### ISSUE TITLE
Waku V2 Metrics

### ISSUE THREAD

**Issue by decanus** [status-im/nim-waku#324]
# Problem

We currently have a metrics [dashboard for Waku V2](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&refresh=5m), this was recently created as part of the scope of issue #256. However, it seems as though the metrics are not correct and there is information missing that could be deemed important.

# Acceptance Criteria

 - The metrics no longer show `0` for all libp2p related metrics, this is incorrect unless the cluster was not set up correctly.
 - We add relevant metrics that could aid in debugging, for example the amount of error messages and warnings present in a nodes logs.

**Comment by oskarth** [comment]
What do we think are relevant metrics? Pubsub peers seems useful, e.g.

**Comment by oskarth** [comment]
Ping on this @decanus

**Comment by jm-clius** [comment]
The following observations:
1. Most metrics (except for `total_messages`, see below) work correctly if running a local `wakunode2`, Prometheus and Grafana server, which suggests that this is related to the cluster setup. This will likely be fixed by https://github.com/status-im/infra-nim-waku/pull/3 and https://github.com/status-im/nim-waku/pull/348.
2. However, the only metric defined for `wakunode2`, namely `total_messages`, is declared but never set/incremented in the code. I will fix this.
3. We should define at least some metrics related to `filter`, `store`, `swap` functionality, debugging etc.
4. The grafana dashboards under `/metrics/`, and documented [here](https://github.com/status-im/nim-waku/tree/master/waku/v2#using-metrics), are outdated and should be updated for Waku v2.
