### ISSUE TITLE
Sketch out Waku v2 making API smaller, separate key crypto ops

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#39]

**Comment by oskarth** [comment]
@kdeme created a skeleton issue, please fill out with details as you see fit and we can discuss on Monday

**Comment by kdeme** [comment]
### Current state

Nim-waku currently has 2 sets of user Waku related APIs.
1. JSON RPC API as is [specified here](https://github.com/vacp2p/specs/blob/master/specs/waku/waku-rpc-api.md) and [implemented here](https://github.com/status-im/nim-waku/blob/master/waku/node/v1/rpc/waku.nim).
2. Nim API as is specified nowhere (everything below this line: https://github.com/status-im/nim-waku/blob/master/waku/protocol/v1/waku_protocol.nim#L476)

In nim-waku, API 1. Uses 2.
AFAIK, status-go has implemented the JSON RPC API + a set off wakuext calls. As a separate task, it should be revised which of these wakuext calls are still required and waku only related (e.g. not doing functionality of a layer above).


Now, there are some questions to ask.

### Does the JSON RPC API need to handle all the key generation, storage, deletion, etc.?
As can be seen in the specification, the JSON RPC API has a whole set of calls that have to do with the the management of asymmetric and symmetric keys. These stored keys are typically referred to with a generated random identifier, which can be used for other rpc calls.

I see three steps that can be taken here:
1. Keep as is.
2. Remove the management of the keys with its random id's. And instead pass in the key (public key or symmetric key) for posting and the key (private key or symmetric key) for subscribing directly.
3. Action 2 + don't do any encryption/decryption and signing in Waku API. Instead, pass in the already signed & encrypted payload, and subscribe to receive all messages on a topic ("application" layer will have to deal with messages that it can't decrypt).

In all 3 steps, the subscribe mechanism with a filter is still used. But one can also still poll for messages.

**Step 2**
Pros:
- Waku API simplification: The API can become a whole lot smaller.
- Key management separated from Waku: Allows for handling it in a generalized and/or specific way in the application.

Cons:
- Still need to pass in the the private key or symmetric key for decryption (filter subscribe) and the public key or symmetric key for each message post. And similar for signing the data.

Perhaps the system of the identifiers had to some users the benefit of the layer above not having to get or hold the keys all the time. But I'm curious if this was really beneficial in any application. In fact, there was a time that the code in status-go was altered to provide deterministic identifiers. Which only shows that there was the key -> identifier -> key remapping flow going on to circumvent this way of API.

**Step 3**
Pros:
- All the pros of 2
- No more storage of the private key data on the node that runs the JSON RPC API. This would allow for a more secure usage.
- Encryption is also done a layer up (as it already done usually anyhow, see question below), which allows for upgrading/changing the encryption and key and signature schemes.

Cons:
- The layer up will need to deal with decryption and more importantly with messages that are not intended for this user (same topic but not able to decrypt). And it will have to deal with signing that data before encryption, and validating the signature on incoming messages.

Which triggers the next question...

### Do we still need encryption defined in Waku at all?

The state is actually that currently the actual Waku Protocol does not define the envelope data needs to be encrypted/signed. Instead it is defined in the separate page: https://github.com/vacp2p/specs/blob/master/specs/waku/envelope-data-format.md . Not sure if that means it is mandatory or not by spec.

Also, Encryption on top of this in the Status-go application (Double Ratchet +  X3DH) makes it obsolete. I guess it is only still used for public chats (Not sure, might have changed also). The signature part might be actually the most necessary part still.

We could also opt for a default but NOT mandatory encryption/signature scheme.

**Regarding the current nim-waku state:**
The Nim API (Used by the JSON RPC API, see intro) already and always has allowed to not do encryption/decryption and signing of the envelope data, practically allowing for a higher layer to do this work. This has been like this because originally the Whisper EIP did not have this as mandatory, and the current Waku specification is interpreted the same (but that might be invalid).

It would probably be a good idea to have the Nim API & the JSON RPC API act in the same way (mostly the same calls, same restrictions, etc.).

**Comment by kdeme** [comment]
One item not to forget, is that in the payload specification not only encryption/signing is defined, but also the padding of the data.
I believe this was always there for privacy reasons, not to be able to tag a set of messages to a specific application, or worse, a user.

This is actually an important item for Waku, as it very privacy related, and Waku is after all the privacy transport layer. 
It would be great to take this a step further though, and look into formats that e.g. mixnets or others use. And see what is done there and how this can be done/applied in Waku.
Interesting one here to start would be Sphinx (Used by Nym and Lightning Network): https://cypherpunks.ca/~iang/pubs/Sphinx_Oakland09.pdf

**Comment by cammellos** [comment]
> Also, Encryption on top of this in the Status-go application (Double Ratchet + X3DH) makes it obsolete. 

Currently we don't use the encrypted header version of the double ratchet, so the header is in clear text, which would reveal metadata, that's possible because of waku encryption.

If we take a way waku encryption, we'd have to use the encrypted header version of the protocol (https://signal.org/docs/specifications/doubleratchet/#double-ratchet-with-header-encryption).
That requires changes as it's currently not supported.
It would  work essentially like waku/whisper, you try all the keys to decrypt the header, it's up to you to find a reasonable way to limit the the keys tried.

**Comment by oskarth** [comment]
@kdeme FYI I added empty docs here https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md - feel free to edit namespace if you want.

Immediate consumer of docs would be us and specifically Stimbus through status-waku (cc @siphiuel @Samyoul)

**Comment by oskarth** [comment]
@kdeme If this issue is too big, can we please cut it up into smaller issues with specific problem and acceptance criteria? Ideally so it can be finished on the order of a few days. Right now it isn't very clear what it means to finish this issue or what is to be done.

**Comment by oskarth** [comment]
https://github.com/status-im/nim-waku/issues/60

**Comment by oskarth** [comment]
@kdeme can we please make a smaller issue out of this that can be completed over a few days, as opposed to being pending for weeks?

**Comment by kdeme** [comment]
Perhaps this is an OK first go at it: https://github.com/status-im/nim-waku/pull/50

I can create a second issue for follow up on this as the protocol spec further develops

**Comment by kdeme** [comment]
New issue created: https://github.com/status-im/nim-waku/issues/61
