### ISSUE TITLE
Bump submodules

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#43]
When I do a naive

> git submodule foreach "(git checkout master; git pull)&" 

I get errors like:

> /home/oskarth/git/github.com/status-im/nim-waku/vendor/nim-eth/eth/p2p/rlpx_protocols/whisper/whisper_types.nim(477, 42) Error: attempting to call undeclared routine: 'formatFloat'

It'd be good if we can find a workflow where we don't need to care about this kind of stuff. Changelog with clear steps to fixing broken/changing stuff, upgrading consumers in one go, etc.

**Comment by kdeme** [comment]
Well, while I very much understand that being annoying, I think nim-eth is still so much in flux that it would be very cumbersome too foresee a proper Changelog.
 
I think for now what can be done, is that for each batch of changes (say a PR) in nim-eth, the repositories that depend on it also get bumped immediately so that issues are seen fast (ideally tested before PR gets merged).
I tend to do this immediately for nim-beacon-chain, and usually also for nim-waku. But sometimes nim-waku is a bit left in the dark due to time constraints, or simply forgotten. And others are not always aware of the nim-waku dependencies.

**Comment by kdeme** [comment]
Done in https://github.com/status-im/nim-waku/pull/45
