### ISSUE TITLE
Waku store: index out bounds and incomplete number of messages being returned

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-waku#471]
There are two scenarios where this error happens:

1. If the topic being requested only has a single message stored, the query will fail and no result will be returned.
The logs in nim-waku will show the following
```
DBG 2021-04-08 18:11:09.890-04:00 A future has failed, enable trace logging for details topics="libp2p connmanager" tid=464160 file=errors.nim:22 error=ResultError
```
While the client doing the query will end with an error due to the stream being closed. go-waku displays this error:
```
2021-04-08T18:11:09.878-0400	ERROR	wakustore	could not read responseEOF
```
2. If the topic being requested has a number of messages < `pageSize`, it will return N messages - 1, 
i.e.: if it only has messages *A*, *B* and *C* stored, the query will return only *A* and *B*, (but it will not include *C* but should)

I think these errors happens due to a index out of bounds error while attempting to calculate the start and end for the list of messages being returned (var `s` and `e`).

for example imagine this scenario: there is only one message in `messageList`, and `foundIndex` returns a `0`, and then a query is received with a `pageSize: 10`,  then in this code:
```nim
let remainingMessages= msgList.len - foundIndex - 1
# the number of queried messages cannot exceed the MaxPageSize and the total remaining messages i.e., msgList.len-foundIndex
retrievedPageSize = min(int(pageSize), MaxPageSize).min(remainingMessages)  
if initQuery : foundIndex = foundIndex - 1
s = foundIndex + 1  # non inclusive
e = foundIndex + retrievedPageSize 
```
We end up with the following values
- `remainingMessages`  == 0
- `retrievedPageSize` == 0
- `foundIndex` == -1
- `s` == 0
- `e` == **-1**

causing later `newCursor = msgList[e].index` to fail because of `e` being -1.

A similar scenario also happens when the order is BACKWARD

**Comment by staheri14** [comment]
None of these scenarios are error, they are the expected behaviour of pagination. Let me clarify it.
In pagination, the message that matches the cursor (i.e., the message corresponding to the `foundIndex` in the code) is excluded from the retrieved list of messages. The assumption is that the querier already has the message corresponding to that cursor. 

> If the topic being requested only has a single message stored, the query will fail and no result will be returned.
The logs in nim-waku will show the following
DBG 2021-04-08 18:11:09.890-04:00 A future has failed, enable trace logging for details topics="libp2p connmanager" tid=464160 file=errors.nim:22 error=ResultError

In the above case, the pagination part of the query should have an empty cursor so that the querier can fetch that single message. Recall that if the cursor matches that single message, then that message will not be included in the response which means an empty list in this example.

> If the topic being requested has a number of messages < pageSize, it will return N messages - 1,
i.e.: if it only has messages A, B and C stored, the query will return only A and B, (but it will not include C but should)

In this case, the cursor matches A (or C), which will result in the retrieval of {B,C} (or {A,B}).

Please let me know if that answers your question.

**Comment by richard-ramos** [comment]
Ah but shouldnt Scenario 2 return all the three messages (A, B, C) if i'm doing an initial query (nil cursor) and have a page size of 10?

**Comment by staheri14** [comment]
> Ah but shouldnt Scenario 2 return all the three messages (A, B, C) if i'm doing an initial query (nil cursor) and have a page size of 10?

For an initial query, yes, it should return all of them.

**Comment by richard-ramos** [comment]
> For an initial query, yes, it should return all of them.

I see. Scenario 2 is this case; it is only returning the first two messages and ignoring the third one in a initial query

**Comment by staheri14** [comment]
> > For an initial query, yes, it should return all of them.
> 
> I see. Scenario 2 is this case; it is only returning the first two messages and ignoring the third one in a initial query

I see! then let me check the issue!

**Comment by staheri14** [comment]
@richard-ramos FYI, I opened this PR https://github.com/status-im/nim-waku/pull/479 to address both error cases discussed in here. Please let me know if the problem persists.

**Comment by D4nte** [comment]
Just wanted to confirmed that from js-waku POV, this is fixed :) Thanks!

**Comment by staheri14** [comment]
> Just wanted to confirmed that from js-waku POV, this is fixed :) Thanks!

@D4nte That is Great! Thanks for letting me know 👍
