### ISSUE TITLE
Updating store json rpc api

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#489]
## Problem
Following the change in the  store protocol's `HistoryQuery` as explained in this PR https://github.com/status-im/nim-waku/pull/488, the  store json rpc api https://github.com/status-im/nim-waku/blob/2edd79a95475f2b4fa54b4b2fad906ac88d6d576/waku/v2/node/jsonrpc/store_api.nim#L20  is also expected to accommodate this new structure.  
More specifically the `topics: seq[ContentTopic` shall be replaced by `topics: seq[HistoryContentFilter]`. However, an attempt to update the proc signature resulted in an error in the following test
https://github.com/status-im/nim-waku/blob/17cfc32c4fda5054d82e00710d46b21e54d792ed/tests/v2/test_waku_bridge.nim#L82
in which the `len` is zero instead of one.

This issue is to identify the cause of the error. 

**Note**: Currently, the  set of input `topics` are converted to their `HistoryContentFilter` equivalence inside the proc. This works fine with no error.  However, the anonymous proc signature is left untouched.

**Comment by jm-clius** [comment]
Mmm, it seems unlikely that this error is directly caused by a change in how the bridge operates, since it does not make use of `store` protocol. More likely the test is failing because of interference from another, earlier unit test, either because:
1. That test is also failing and consequently does not clean up resources as well as it should.
2. That test does not `stop()` all nodes it started and this interferes with the node that the bridge test is starting.

Is this the first test that fails in the train? I'd especially check the jsonrpc tests.

**Comment by staheri14** [comment]
Thanks @jm-clius! the error was due to another failed unit test.
