### ISSUE TITLE
unsubscribe and deleteMessageFilter are identical

### ISSUE THREAD

**Issue by siphiuel** [status-im/nim-waku#49]
Stumblen upon this together with @Samyoul : the implementations for `unsubscribe` and `deleteMessageFilter` in `waku/node/v1/rpc/waku.nim` are identical:

```
    result  = node.unsubscribeFilter(id.string)
    if not result:
      raise newException(ValueError, "Invalid filter id")
```

This is probably not intended.

**Comment by kdeme** [comment]
Yes, both implementations in the RPC calls are the same. This because the underlying `subscribeFilter` and `unsubscribeFilter` are usable for both the callback approach and the polling approach (depends on whether you pass a handler or not to `subscribeFilter`).

Why have both calls then you might ask? Simply because it is according to specification (original whisper v6 & now the one we have for waku). It can be that other implementations need a different implementation here for each of the two calls.

That being said, the `subscribe` RPC call is currently not implemented. So the `unsubscribe` implementation doesn't matter much. It might be that depending on implementation of `subscribe`, we possibly need to add some code to `unsubscribe`.

**Comment by kdeme** [comment]
Not really an issue as explained above so I will close this.
