### ISSUE TITLE
Plan new testnet Huilong

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#555]
We had Nangang and Dingpu testnet https://github.com/status-im/nim-waku/tree/master/docs/tutorial, since then a lot has changed and it is time for a new testnet. Major features include: multiple implementations, dogfooding, etc.

Blocked by Discord bridge so we can first dogfood https://github.com/status-im/infra-nim-waku/issues/8

## Checklist

- [x] Discord bridge deployed and core devs using chat2 daily
- [x] New subway name
- [ ] List major changes / support client versions
- [ ] Scope of what we want to test and how (daily use, stress test, public, etc?)
- [ ] Possibly an update post
- [ ] Tweet announce

Anything else that comes to mind?

## Possible ideas

- Make it public, encourage more people to join
- Have people run own nodes
- Stress test FT store protocol

**Comment by oskarth** [comment]
cc @jm-clius @staheri14 @D4nte @richard-ramos for thoughts

**Comment by jm-clius** [comment]
Some things that I'd like to see demonstrated/tested, roughly in order of priority:
1. Demonstrate multi-client support, with bridging to Discord (the obvious one)
2. Demonstrate a (Nim) node with only `filter` and `lightpush` capabilities participating (what, in a previous life, I might have called a "light" node 😝)
3. Demonstrate bridging to v1 (might require dusting off `chat2` payload encryption feature)

As to _how_: all of the above can be done in a single semi-synchronised session (say, people join and participate during the course of a day/week, running their own nodes). I like the idea of making it public.

**Comment by richard-ramos** [comment]
I'd like to see waku in action on a mobile device. 
Perhaps it's possible to create a native chat2 implementation for android and IOS?

**Comment by D4nte** [comment]
> I'd like to see waku in action on a mobile device.
> Perhaps it's possible to create a native chat2 implementation for android and IOS?

You can use https://status-im.github.io/js-waku/ on your mobile phone/browser :)

**Comment by D4nte** [comment]
> We had Nangang and Dingpu testnet [https://github.com/status-im/nim-waku/tree/master/docs/tutorial](https://github.com/status-im/nim-waku/tree/master/docs/tutorial?rgh-link-date=2021-05-19T02%3A12%3A57Z), since then a lot has changed and it is time for a new testnet. Major features include: multiple implementations, dogfooding, etc.

Can you please clarify why  we need a new testnet? I would expect this kind of migration to be driven by major non-backward compatible changes. However, we have been using the same testnet across backward compatible changes (e.g. use of protobuf format for chat message).

>     * [ ]  New subway name

By "testnet" you mean the content topic used by the chat app, right? Should we try to tackle https://github.com/vacp2p/rfc/issues/364 so that the content topic we uses matches the format that we expect developers to use for their own apps?

**Comment by oskarth** [comment]
@jm-clius agree
@richard-ramos how far away are we from go-waku on mobile?
@D4nte testnet != new cluster fleet nor necessarily new content topic, it is about dogfooding and trying out capabilities/clients, same motivation as all the previous internal testnets we had as well what eth2 has been doing etc

**Comment by D4nte** [comment]
@richard-ramos When you are talking about native chat2 for android and iOS, did you think go-waku so it matches Status' architecture or did you think react native using js-waku?

**Comment by richard-ramos** [comment]
> how far away are we from go-waku on mobile?

We need https://github.com/status-im/status-go/pull/2179 and https://github.com/status-im/status-go/pull/2205 to land first into `develop` branch, and then work on creating a status-react version that uses the wakuv2 configuration instead of wakuv1. In #pm channel there's some discussion about possible next steps.

> When you are talking about native chat2 for android and iOS, did you think go-waku so it matches Status' architecture or did you think react native using js-waku?

I was thinking in both go-waku and nim-waku being used as libraries for any native applications developed in Swift or Kotlin.

**Comment by oskarth** [comment]
New testnet name: Huilong 迴龍

Content topic: `/waku/2/huilong/proto`

**Comment by oskarth** [comment]
https://twitter.com/vacp2p/status/1405390369173299200 closing out
