### ISSUE TITLE
Decide on protobuf solution

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#58]
# Problem

Currently, there are two libraries that implement protobuf:

- https://github.com/status-im/nim-protobuf-serialization
- minprotobuf

NPS is more of a user friendly black box approach whereas minprotobuf requires more work. Minprotobuf is what NBC is using in production though, it is part of audit and is 100% compatible with proto2 using in nim-libp2p, whereas NPS has some kinks to work out to be fully compatible.

To complicate matters, we use proto2 for WakuSub/PubSub and libp2p, but the actual payloads in e.g. Status protocol would be proto3 (https://specs.status.im/spec/1#protobuf).

## Suggested solution

See PR thread here https://github.com/status-im/nim-waku/pull/47/files#r454087497 for other thoughts. My proposal:

### 1. Defer to NBC
I don't think it makes sense for Vac/Waku to push use for NPS support at the libp2p layer until this is merged upstream by Nimbus. There are likely kinks to work out, and we better defer to their judgement and expertise than rabbit hole ourselves with protobuf issues. Once https://github.com/status-im/nim-libp2p/pull/199 is merged we can move.

### 2. Payloads

At the same time, assuming NPS proto3 support is flawless, we could consider using it for data payloads. However, this would likely happen at Stimbus layer, not in nim-waku other than as a toy example.

It isn't currently clear to me if using two implementations like this would have any issues. In any case, they can be seen as essentially two different protocols, like Whisper and Waku v1.

## Links

WIP https://github.com/status-im/nim-libp2p/pull/199
Libp2p proto2 https://github.com/libp2p/specs/issues/281
NPS proto2 proto3 mismatch https://github.com/status-im/nim-protobuf-serialization/issues/4
Some NPS todos https://github.com/kayabaNerve/nim-protobuf-serialization/issues/32
Origin https://github.com/status-im/nim-waku/pull/47#discussion_r454087497

**Comment by arnetheduck** [comment]
the serialization and deserialization from and to protobuf is somewhat orthogonal to having a natural in-process representation of the serialized data - in general, protobuf message types make poor implementation types (the type system in protobuf for example is different compared to that of nim - there is a translation tax) and vice versa - ie when designing the protobuf protocol, a `.proto` should be used, and when designing code, the most natural in-process representation should be used. 

solutions like nps try to take a shortcut by using the same object type for protocol specification and in-process representation - this is a somewhat smelly approach in general that fails to isolate the protocol from the code and logic in any meaningful way - it's useful for prototyping, but code and protocols generally don't have the same tradeoffs - good code will usually insulate one from the other using separate types - indeed, this is why `.proto` files use a different language. 

a classic example of where this approach falls short and causes security issues is that it's easy to use the type that describes the serialization as-if it its contents were secure and validated - something that comes out of NPS however is not secure and validated - it has merely passed the protobuf type validation which is weak.

I generally agree that waku and the status app are poor training wheels for libraries like this - the wrong tradeoffs in the nps library will lead to sub-par protocols that will stay with us for a long time and are significantly harder to upgrade in a backwards-compatible way than fixing nps which is a recompile away.

since anything that is related to protocol/wire serialization and deserialization should be isolated in the code in a separate module,  using the libp2p solution is trivial: there are two functions to write that serialize and deserialize and there should be no further impact to the code - switching from one to the other should be extremely cheap - if it's not, the code in question is not properly written / isolated to begin with. 

this way, we can let nps progress independently of waku and friends, and use the code developed in waku to drive feature-completeness in nps by porting it. trying to port libp2p to nps highlighted several semantic issues in nps that remain unsolved (the libp2p PR is not merged because it's incorrect) - until those issues have been solved, there's little point in subjecting _more_ code to it.

**Comment by zah** [comment]
All planned changes to nim-protobuf-serialization concern only ProtoBuf v2. Furthermore, the changes are rather trivial and boil down to adding an additional proto2-specific `Option` type and renaming a pragma. Some development time will need to be invested in learning the semantics of Protobuf and writing code against `miniprotobuf`. One could easily argue that the same time will be better invested in "fixing" NPS (even the time we spent in these ongoing discussions already exceeds the needed time to implement the changes).

Existing Proto3 users (such as the MVDS and the Payload protocols) should not even have this dilemma. They can use the new library without concerns.

The general claim that protocol types should be kept separate from the "validated" application types is poorly justified in my opinion. If such a strong separation on the type system level is required, the best tool for the job in Nim would be the distinct types. You can have a `RawMessage` network message type that passes through a `validate` function that blesses and promotes the value to a `ValidatedMessage` type. Seldom, you would need to repackage the data inside the message into a different structure and only then you would need to pay the price of additional type definitions, extra steps in the code and run-time copying.

**Comment by oskarth** [comment]
Personally I'd probably like to see the `.proto` file abstraction for protobuf v3 to be supported by NPS (https://github.com/status-im/nim-protobuf-serialization/issues/4#issuecomment-662206895) before we start to use it for Waku payloads

**Comment by decanus** [comment]
I am currently using minprotobuf everywhere. So we can probably use that as an implicit decision for us right now.

**Comment by oskarth** [comment]
Let's close it for now and we can revisit it if things change with proto file support etc.

**Comment by zah** [comment]
The protobuf-serialization library has been updated with to address the critique of not supporting the ProtoBuf2 semantics properly in the following PR:

https://github.com/status-im/nim-protobuf-serialization/pull/5

Support for parsing Proto3 file has been added here:
https://github.com/status-im/nim-protobuf-serialization/pull/6

**Comment by oskarth** [comment]
Nice!

@zah is this used in the Nimbus code base now?

@decanus did you see this? If you used it, did you find any blockers for it?
