### ISSUE TITLE
21/WAKU2-FTSTORE: Both startTime and endTime but be pass to enable temporal filtering

### ISSUE THREAD

**Issue by D4nte** [status-im/nim-waku#706]
# Problem

According to the [specs](https://rfc.vac.dev/spec/21/):

> - start_time: this field MAY be filled [...]. The messages field of the corresponding HistoryResponse MUST contain historical waku messages whose timestamp is larger than or equal to the start_time.
> - end_time:  this field MAY be filled [...]. The messages field of the corresponding HistoryResponse MUST contain historical waku messages whose timestamp is less than or equal to the end_time.
> 
> If both start_time and end_time are omitted then no time-window filter takes place.

Thus:
- `start_time` and `end_time` behaviors are defined separately.
- The time-window filter is disabled when both `start_time` and `end_time` are omitted.

Hence, I would expect time-window filter to be enabled when only one field is passed.
E.g., if `start_time` is filled, then _messages field of the corresponding HistoryResponse MUST contain historical waku messages whose timestamp is larger than or equal to the start_time._

However, nim-waku's behaviour is such as both `start_time` and `end_time` must be passed for time-window filter to be enabled:

https://github.com/status-im/nim-waku/blob/4aae5c55ac59c1f893f80cca642d2b55e99ecb42/waku/v2/protocol/waku_store/waku_store.nim#L397

# Solution

Please review and either correct the spec or the code.
In this instance, I believe that the code should be aligned with the spec as I can see a benefit in having open-ended time window for Browser/Mobile clients.
If a client loses connectivity, they may want to only specify a `start_time` matching when connectivity was lost, without specifying an `end_time`.

**Comment by staheri14** [comment]
Thanks @D4nte for reporting the issue! I am going to clarify it in the specs i.e., either both start and end times should be determined or none.
However, due to the pagination, I suggest not enabling an open-ended time query, this will cause issues, see example below: 

- Bob (as a store/relay node) wants messages from time t0 up to t1 but instead queries [t1-unkown] from Alice
- Alice (as the store node) currently has messages from t0-t1
- Alice sends the first page with messages whose timestamp>t0
- Bob gets the query response and sends his second query for the second page
- In the meanwhile, Alice is listening to the network and gets more messages and she obtains messages with timestamp > t1 therefore, for the second query of Bob, she will include the new messages as well (those are out of Bob's intended time window i.e., t0-t1).
- ... this process goes like this and Bob has to determine when to stop querying (because Alice may always have some more messages to return).

In this example, as Bob is also listening to the network (he is a store/relay node), all the messages that he receives from Alice after t1 are duplicates.

In the specs, we have explained how to set an upper bound for the time window to make sure that all the past messages up until the node's current online time be retrieved.

Please let me know whether this makes sense.

**Comment by jm-clius** [comment]
Jumping in without having looked at either spec/implementation in detail, but wouldn't requiring Bob to include the timing criteria in every subsequent query solve the state issue? Or, perhaps changing spec  so that an open time query is always responded to with BACKWARDS pagination, starting from the latest that Alice is storing until Bob stops querying/the beginning of history is reached. Just a thought. :)

**Comment by staheri14** [comment]
Thanks @jm-clius for your comment! :) 
> Jumping in without having looked at either spec/implementation in detail, but wouldn't requiring Bob to include the timing criteria in every subsequent query solve the state issue?

The timing criteria are the same across all the paging requests, e.g., the first query has t0-t1 and in response, Bob gets the first page, the next query is again for t0-t1 and the response contains the second page, and so on.
Given that the time window is the same, its inclusion does not solve the issue. 


> Or, perhaps changing spec so that an open time query is always responded to with BACKWARDS pagination, starting from the latest that Alice is storing until Bob stops querying/the beginning of history is reached. Just a thought. :)


Yes, it solves the issue, however, this solution restricts the pagination options i.e., no FORWARD pagination is supported for an open-end time query.  I am not saying we should not have exceptions like this, however, I am not completely clear about what is the problem with the current specs, in the specs, we advise the querier to offset the time window by 20 seconds to make sure that all the messages within the intended timeline will be fetched from the store node.  The 20-sec offset is the approximate upper bound on the nodes asynchrony (e.g. the current Unix epoch time of Alice and Bob systems may be 20-sec apart), it can be also set to a higher value if the querying node wants so. I think adding the 20-sec offset to the time window should cover the concern raised in the issue. 
Please let me know if I am missing something. :)

**Comment by D4nte** [comment]
>     * Bob (as a store/relay node) wants messages from time t0 up to t1 (t1 is Bob's current time) but instead queries [t1-unkown] from Alice

Do you mean _[t0-unknown]_ ?

**Comment by D4nte** [comment]
I see how the pagination makes the task difficult. Thanks for the clarification .Should this be moved to the spec repo then?

**Comment by staheri14** [comment]
> I see how the pagination makes the task difficult. Thanks for the clarification .Should this be moved to the spec repo then?

Yes, moving it to the spec makes sense! @D4nte

**Comment by staheri14** [comment]
@D4nte I added a clarification in this regard in this PR https://github.com/vacp2p/rfc/pull/459
Please let me know whether this addresses your concern.

**Comment by D4nte** [comment]
Thanks. Solved with vacp2p/rfc#459
