### ISSUE TITLE
Docker cannot find the rln lib

### ISSUE THREAD

**Issue by staheri14** [status-im/nim-waku#921]
This is to track an issue regarding the inclusion of the rln lib in the nim-waku docker image.
The problem is that when copying the rln lib into the docker image as instructed in the following file, https://github.com/status-im/nim-waku/blob/ee96705c7fbe4063b780ac43b7edee2f6c4e351b/Dockerfile#L47, the docker complains that it cannot locate the file. This issue is to track this problem.

**Comment by kaiserd** [comment]
A summarizing comment after testing this with @staheri14:

[The Dockerfile](https://github.com/status-im/nim-waku/blob/d0cf3ed1f9299618bbab920c66ee06372f24c1fd/Dockerfile#L21) [overrides](https://www.gnu.org/software/make/manual/make.html#Overriding) the `NIM_PARAMS` variable. So even when setting this line in the Dockerfile to


```
RUN make -j$(nproc) $MAKE_TARGET NIM_PARAMS="$NIM_PARAMS" RLN=true
```

, the RLN submodule will not be compiled because make will not allow overriding variables that have been passed via the commandline.
For instance, [this line](https://github.com/status-im/nim-waku/blob/d0cf3ed1f9299618bbab920c66ee06372f24c1fd/Makefile#L73) will have no effect, even if `RLN=true`.

Two ways of fixing this are:

Changing [this line in the Dockerfile](https://github.com/status-im/nim-waku/blob/d0cf3ed1f9299618bbab920c66ee06372f24c1fd/Dockerfile#L21)  to 

```
RUN make -j$(nproc) $MAKE_TARGET NIM_PARAMS="$NIM_PARAMS" RLN=true
```

removing the `NIM_PARAMS="$NIM_PARAMS"`.

This can be used for local testing, but is not mergeable as it is a breaking change. Scripts, e.g. our [Jenkins config](https://ci.status.im/job/nim-waku/job/deploy-v2-test/build?delay=0sec) use this.

Another possibility is adding `RLN=true` like listed above:


```
RUN make -j$(nproc) $MAKE_TARGET NIM_PARAMS="$NIM_PARAMS" RLN=true
```

and additionally setting `-d:rln` on the commandline when building the docker image like so:

```
docker build -t nwaku . -f Dockerfile --build-arg=NIM_PARAMS='-d:rln -d:disableMarchNative -d:chronicles_colors:none -d:insecure -d:chronicles_log_level=DEBUG'
```

or alternatively the `RLN=true` could be passed as a docker build argument, too, in case RLN support should stay optional.

This seems like unnecessary repetition because `RLN=true` should trigger `-d:rln` to be set. But make does not allow this.


I will open an issue for this soon, as it also affects other flags added to `NIM_PARAMS` like the discv5 `protocol-id`.

Solutions comprise but are not limited to:

* add `override` to `NIM_PARAMS` in the Makefile.
* introduce a second variable for Nim parameters in the Makefile: one set within Makefile, and one that is supposed to be set via the commandline
  - note: the one for use within the Makefile could still be overridden, but our spec would suggest not to do this to avoid confusion


Also, the alpine version should be bumped to `3.15`. The rust version in `3.12` is too old and does not support all necessary features.


cc @jakubgs

**Comment by jakubgs** [comment]
What's the problem with adding `-d:rln` to `NIM_PARAMS` though?

**Comment by staheri14** [comment]
> What's the problem with adding -d:rln to NIM_PARAMS though?

In the case of rln, there is no issue, but it is somewhat redundant and can be avoided if we could have the `override` option in the make file (I am not suggesting adding this option as it may cause other complications, this is just my interpretation of the problem).
The situation is that there is already a makefile argument `RLN` which controls all the behavior related to the rln lib e.g., enabling the compiler flag `-d:rln`, building the rln rust library, etc. However, if this argument gets set in the docker file in line https://github.com/status-im/nim-waku/blob/5ceef37e15a15c52cbc589f0b366018e81a958ef/Dockerfile#L21, 
```
RUN make -j$(nproc) $MAKE_TARGET NIM_PARAMS="$NIM_PARAMS" RLN=true
```
Its effect on the nim parameters will be overridden by the parameters set when running the docker build command. Thus, the `rln` flag needs to be manually sent as an argument to the docker build to account for this.

**Comment by kaiserd** [comment]
For the RLN problem, adding a new variable `RLN` to the Dockerfile, as @staheri14 already did, is a good solution.

> What's the problem with adding `-d:rln` to `NIM_PARAMS` though?

In general, all desired parameters that we add in the Makefile would have to be added in the Dockerfile (or when building the container), too.
Imo, that is error-prone, and some parameters might be missed.
We just discussed the problem of the missing `-d:discv5_protocol_id:d5waku`, which is necessary for the current version of [33/WAKU2-DISCV5](https://rfc.vac.dev/spec/33/).
If someone is not aware of the fact that the Dockerfile overrides `NIM_PARAMS`, this might lead to confusion.
