### ISSUE TITLE
Cannot discover nodes in status.test

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-waku#927]
I redeployed the status.test fleet adding the parameter `-d:discv5_protocol_id:d5waku`. I was expecting to discover the three nodes from status.test fleet (https://fleets.status.im/), but when testing using nim-waku, the only node discovered is the bootstrap node i'm connecting to.

I tried using two instances of nim-waku using the same bootstrap node, and they can't discover each other either. I do see this message a lot in the logs:
```
DBG 2022-03-30 10:55:22.814-04:00 Message request to bootstrap node failed   topics="discv5" tid=2628719 file=protocol.nim:470 enr=enr:-JK4QBjnN1Rz22q8OpMljXHQz08Fl8HE22mq08B-eEc5yb_TIsYI8_B7RtR2XD8IvWb1B85Tof0d46up72xmoHJU8_oBgmlkgnY0gmlwhJRnt-eJc2VjcDI1NmsxoQK_pc-GzzcR3el-rRNFSxrtxwPIGBEBrcJnL92xtwHa24N0Y3CC6mSDdWRwgiMrhXdha3UyAw
```

cc: @iurimatias

**Comment by kaiserd** [comment]
The issue is fixed :). The main problem was a firewall blocking discv5 requests.
Instead of UDP port 9000, TCP port 9000 was open.
Thanks @jakubgs for the [fix :)](https://github.com/status-im/infra-status/commit/847679f9).

As @jm-clius let me know, the test fleet nodes do not have each other as bootstrap nodes. So, using the `ENR` of a test fleet node as bootstrap ENR,  just retrieving one node via discv5 for now is OK.

Thanks again @jakubgs @jm-clius for the help with this issue :).

**Comment by richard-ramos** [comment]
Thank you! status.test is working fine now :)

**Comment by jm-clius** [comment]
Thanks for this and good work, @kaiserd!
